---
- name: Downloading {{ item.dest | basename }}
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0775'

- name: Installing {{ item.dest | basename }}
  ansible.builtin.apt:
    deb: "{{ item.dest }}"
