---
- name: Xdebug | Ensure xdebug is installed and enabled
  ansible.builtin.shell: |
    set -o pipefail
    /usr/bin/php{{ php_default_version_debian }} -m | grep 'xdebug'
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: false
  register: php_xdebug_check_install

- name: Xdebug | override default configuration for xdebug
  ansible.builtin.template:
    src: xdebug.ini.j2
    dest: /etc/php/{{ php_default_version_debian }}/mods-available/xdebug.ini
    mode: '0644'
  when: php_xdebug_check_install.rc == 0

- name: Ensure xdebug is removed
  ansible.builtin.apt:
    name: "php{{ php_version }}-xdebug"
    state: absent
