---
- name: Cassandra | List installed packages
  ansible.builtin.package_facts:

- name: Cassandra | Manage multiarch-support package
  when: "'multiarch-support' not in ansible_facts['packages']"
  block:
    - name: Cassandra | Download multiarch-support package
      ansible.builtin.get_url:
        url: https://archive.ubuntu.com/ubuntu/pool/main/g/glibc/multiarch-support_2.27-3ubuntu1.6_amd64.deb
        dest: /tmp/multiarch-support_2.27-3ubuntu1.6_amd64.deb
        mode: '0644'
        checksum: sha256:70c0efcf6299aeedcf374e54eeb826f9f0e49c3359267aa6e61bf749dde449c1
      register: download_multiarch_support

    - name: Cassandra | Install multiarch-support package
      ansible.builtin.apt:
        deb: /tmp/multiarch-support_2.27-3ubuntu1.6_amd64.deb
      when: download_multiarch_support is changed

    - name: Cassandra | Remove multiarch-support package
      ansible.builtin.file:
        path: /tmp/multiarch-support_2.27-3ubuntu1.6_amd64.deb
        state: absent
      when: download_multiarch_support is changed

- name: Cassandra | Manage libssl1.1 package
  when:
    - ansible_facts['distribution'] == "Debian"
    - ansible_facts['distribution_major_version'] | int > 11
    - "'libssl1.1' not in ansible_facts['packages']"
  block:
    - name: Cassandra | Download libssl1.1 package
      ansible.builtin.get_url:
        url: https://ftp.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1w-0+deb11u1_amd64.deb
        dest: /tmp/libssl1.1_1.1.1w-0+deb11u1_amd64.deb
        mode: '0644'
        checksum: sha256:aadf8b4b197335645b230c2839b4517aa444fd2e8f434e5438c48a18857988f7
      register: download_libssl1_1

    - name: Cassandra | Install libssl1.1 package
      ansible.builtin.apt:
        deb: /tmp/libssl1.1_1.1.1w-0+deb11u1_amd64.deb
      when: download_libssl1_1 is changed

    - name: Cassandra | Remove libssl1.1 package
      ansible.builtin.file:
        path: /tmp/libssl1.1_1.1.1w-0+deb11u1_amd64.deb
        state: absent
      when: download_libssl1_1 is changed

- name: Cassandra | install build dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ php_cassandra_php_driver_build_dependencies }}"
    - "{{ php_cassandra_php_driver_build_dependencies_extra }}"

- name: Cassandra | ensure cassandra c++ driver is not installed
  ansible.builtin.find:
    paths: /usr/lib/x86_64-linux-gnu/
    recurse: true
    patterns: '*cassandra*'
  register: cassandra_cpp_result

- name: Cassandra | install cassandra c++ driver and dependencies
  ansible.builtin.include_tasks: _download_install.yml
  loop: "{{ php_cassandra_cpp_driver_pkgs }}"
  when: cassandra_cpp_result.matched < 1

- name: Cassandra | check for cassandra php driver
  ansible.builtin.shell: |
    set -o pipefail
    /usr/bin/php{{ php_default_version_debian }} -m | grep 'cassandra'
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: false
  register: php_cassandra_check_install

- name: Cassandra | check cassandra php driver version if installed
  ansible.builtin.shell: |
    set -o pipefail
    /usr/bin/php{{ php_default_version_debian }} -r 'echo \phpversion("cassandra") . \PHP_EOL;'
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: false
  register: php_cassandra_installed_version
  when: php_cassandra_check_install.rc == 0

- name: Cassandra | download and compile cassandra php driver
  block:
    - name: Cassandra | Set working directory
      ansible.builtin.set_fact:
        workdir: /usr/src/php-driver

    - name: Cassandra | download datastax/php-driver from GitHub
      ansible.builtin.git:
        repo: "{{ php_cassandra_php_driver_repo }}"
        version: "{{ php_cassandra_php_driver_version }}"
        dest: "{{ workdir }}"

    - name: Cassandra | compile source code
      ansible.builtin.shell:
        cmd: |
          set -ex -o pipefail
          /usr/bin/phpize{{ php_default_version_debian }}
          mkdir -p {{ workdir }}/build
          cd {{ workdir }}/build
          ../ext/configure --with-php-config=/usr/bin/php-config{{ php_default_version_debian }} > /dev/null
          make clean >/dev/null
          make -j{{ ansible_facts['processor_cores'] }}
          make install
          echo 'extension=cassandra.so' > /etc/php/{{ php_default_version_debian }}/mods-available/cassandra.ini
          phpenmod -v {{ php_default_version_debian }} cassandra
        chdir: "{{ workdir }}/ext"
        executable: /bin/bash
      register: build_cassandra
      changed_when: build_cassandra.rc != 0

    - name: Cassandra | cleanup
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ workdir }}"
      when: php_cassandra_php_driver_cleanup_build | bool
  when:
    - php_cassandra_check_install.rc == 1 or
      php_cassandra_php_driver_version > 'v' + php_cassandra_installed_version.stdout
