---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false
    php_enable_php_fpm: true
    php_memory_limit: "192M"
    php_install_recommends: false
    php_default_version_debian: "{{ lookup('env', 'PHP_DEFAULT_VERSION_DEBIAN') }}"
    php_pecl_extensions_install: "{{ lookup('env', 'PHP_PECL_EXTENSIONS', default='[]') | from_json | default([], true) }}"
    php_extensions_enable: "{{ ['rdkafka', 'zookeeper'] if php_pecl_extensions_install else [] }}"

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"

  post_tasks:
    - name: Confirm PHP configuration is correct.
      ansible.builtin.shell: php -i | grep 'memory_limit.*192'
      changed_when: false
