---
- name: Converge
  hosts: instance
  #become: true

  vars:
    php_enable_webserver: false
    php_enable_php_fpm: true
    php_memory_limit: "192M"
    php_enablerepo: "remi,remi-php82"
    php_install_recommends: false
    php_pecl_extensions_install:
      - apcu
      - redis
    php_extensions_enable:
      - apcu
      - redis

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts.os_family == 'Debian'
      changed_when: false

  roles:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
