---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Add Debian repositories
      when: ansible_facts["distribution"] == "Debian"
      block:
        - name: Install packages
          ansible.builtin.apt:
            name: 
              - python3-debian
              - gnupg2
            state: present
            update_cache: true

        - name: Add Ondrej Sury's apt key (Debian)
          ansible.builtin.get_url:
            url: https://packages.sury.org/php/apt.gpg
            dest: /usr/share/keyrings/sury-php.gpg
            mode: '0644'

        - name: Cassandra | Add bionic security repository
          ansible.builtin.deb822_repository:
            name: ondrej-sury-php
            types: deb
            uris: https://packages.sury.org/php
            suites: "{{ ansible_facts['distribution_release'] }}"
            components: main
            signed_by: /usr/share/keyrings/sury-php.gpg
            state: present
            enabled: true
  
    - name: Use Debian 11 repository for some packages on Debian 13
      when:
        - ansible_facts["distribution"] == "Debian"
        - ansible_facts["distribution_major_version"] | int == 13
      block:
        - name: Set Debian 11 repository
          ansible.builtin.deb822_repository:
            name: bullseye
            types: deb
            uris: http://deb.debian.org/debian
            suites: bullseye
            components: main
            state: present
            enabled: true

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
