---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    # Debian-specific tasks.
    - name: Add ondrej repository for Debian
      when: ansible_distribution == "Debian"
      block:
        - name: Add Ondrej Sury's apt key (Debian)
          ansible.builtin.get_url:
            url: https://packages.sury.org/php/apt.gpg
            dest: /usr/share/keyrings/sury-php.gpg
            mode: '0644'

        - name: Cassandra | Add bionic security repository
          ansible.builtin.deb822_repository:
            name: ondrej-sury-php
            types: deb
            uris: https://packages.sury.org/php
            suites: "{{ ansible_distribution_release }}"
            components: main
            signed_by: /usr/share/keyrings/sury-php.gpg
            state: present
            enabled: true

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
