---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Add Debian repositories
      when: ansible_facts["distribution"] == "Debian"
      block:
        - name: Install packages
          ansible.builtin.apt:
            name:
              - python3-debian
              - gnupg2
              - libzookeeper-mt-dev
            state: present
            update_cache: true

        - name: Add Ondrej Sury's apt key (Debian)
          ansible.builtin.get_url:
            url: https://packages.sury.org/php/apt.gpg
            dest: /usr/share/keyrings/sury-php.gpg
            mode: '0644'

        - name: Cassandra | Add Ondrej Sury's repository in Debian 12 and earlier
          ansible.builtin.apt_repository:
            filename: ondrej-sury-php
            repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
            update_cache: true
            mode: "0644"
            state: present
          when: ansible_facts['distribution_major_version'] <= '12'

        - name: Cassandra | Add Ondrej Sury's repository
          ansible.builtin.deb822_repository:
            name: ondrej-sury-php
            types: deb
            uris: https://packages.sury.org/php
            suites: "{{ ansible_facts['distribution_release'] }}"
            components: main
            signed_by: /usr/share/keyrings/sury-php.gpg
            state: present
            enabled: true
          when: ansible_facts['distribution_major_version'] >= '13'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install librdkafka
      ansible.builtin.include_role:
        name: rgsystemes.librdkafka
