---
- name: Verify
  hosts: instance
  become: true
  gather_facts: true

  tasks:
    - name: Ensure cassandra compiled driver was installed
      ansible.builtin.shell: |
          set -o pipefail
          php -m | grep -qiE 'cassandra'
      args:
        executable: /bin/bash
      register: ext_cassandra
      changed_when: ext_cassandra.rc != 0
