---
name: CI
on:
  repository_dispatch:
    types: CI
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
  schedule:
    - cron: 0 4 * * 1
jobs:

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the codebase.
  #       uses: actions/checkout@v6

  #     - name: Set up Python 3.
  #       uses: actions/setup-python@v6
  #       with:
  #         python-version: '3.13'  # Can't go to 3.14+ until Ansible 13.x

  #     - name: Install test dependencies.
  #       run: pip3 install yamllint

  #     - name: Lint code.
  #       run: |
  #         yamllint .

  molecule:
    name: Molecule
    # needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: debian11
            version: "8.3"
          - distro: debian11
            version: "8.4"
          - distro: debian13
            version: "8.3"
          - distro: debian13
            version: "8.4"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python 3.
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'  # Can't go to 3.14+ until Ansible 13.x

      - name: Install test dependencies.
        run: pip3 install ansible molecule "molecule-plugins[docker]" docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PHP_DEFAULT_VERSION_DEBIAN: ${{ matrix.version }}
